# Generated by Django 4.2.14 on 2024-08-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('BAS', 'Basic'), ('ADD', 'Add')], default='BAS', help_text='Type of the task', max_length=3)),
                ('state', models.CharField(choices=[('PE', 'Pending'), ('RU', 'Running'), ('CO', 'Completed'), ('ER', 'Errored')], default='PE', help_text='State of the task. a task can be ran when PENDING and available_at < now', max_length=2)),
                ('retry', models.IntegerField(default=1, help_text='Available retries before ERRORED')),
                ('data_input', models.JSONField()),
                ('data_output', models.JSONField(())),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_at', models.DateTimeField(auto_now_add=True, help_text='Available_at must be below now for the task to be ran', null=True)),
            ],
        ),
    ]
