# Generated by Django 4.2.14 on 2024-08-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_task_data_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('BAS', 'Basic'), ('ADD', 'Add'), ('DIV', 'Divide')], default='BAS', help_text='Type of the task', max_length=3),
        ),
    ]
